@startuml

start
  :Test setting a field
  in an ingredient to something legal;
    if (Something went wrong?) then (no)
      #palegreen:OK;
      stop
      break
    endif
    ->Yes;
    :Alert "Error with long text";

stop


@enduml